project:
  type: website
  output-dir: docs
  
website:
  title: "geoscience"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true